config/routes.rb
Rails.application.routes.draw do
  root to: "todo_lists#index"
  
  resources :sessions, only: [:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

  resources :todo_lists do
    resources :todo_items
  end


end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :gender, inclusion: {in: %w(male female), message: "Only male and female are allowed"}
  validate :firstname_OR_lastname_null
  validate :male_cantbe_sue

  def male_cantbe_sue
    if gender == "male" && first_name == "Sue"
      errors.add(:first_name, "can't be Sue")
    end
  end

  def firstname_OR_lastname_null
    if first_name == nil && last_name == nil
      errors.add(:first_name, "Can't be NULL")
      errors.add(:last_name, "Can't be NULL")
    end
  end

  def self.get_all_profiles(min_year, max_year)
    self.where("birth_year BETWEEN ? AND ?", min_year, max_year).order(:birth_year)
  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  default_scope {order :due_date}
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :todo_items, dependent: :destroy
  default_scope {order :list_due_date}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile, dependent: :destroy
  has_many :todo_lists, dependent: :destroy
  has_many :todo_items, through: :todo_lists, source: :todo_items, dependent: :destroy

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_user_login
  helper_method :logged_in?, :current_user

  protected
    def ensure_user_login
      redirect_to login_path unless session[:user_id] #Always redirect to login page unless session contains a reviewer id
    end

    def logged_in?
      session[:user_id]
    end

    def current_user
      @current_user ||= User.find(session[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_login, only: [:new, :create]
  def new
    #Login page - direct to views/sessions/new.html.erb.
  end

  def create
    username = User.find_by(username: params[:user][:username])
    password = params[:user][:password]

    if username && username.authenticate(password)
      session[:user_id] = username.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      redirect_to login_path, alert: "username/password is not valid!"
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: "logged out!"
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists/:todo_list_id/todo_items/:id
  # GET /todo_lists/:todo_list_id/todo_items/:id.json
  def show
  end

  # GET /todo_lists/:todo_list_id/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_lists/:todo_list_id/todo_items/:id/edit
  def edit
  end

  # POST /todo_lists/:todo_list_id/todo_items
  # POST /todo_lists/:todo_list_id/todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/:todo_list_id/todo_items/:id
  # PATCH/PUT /todo_lists/:todo_list_id/todo_items/:id.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/:todo_list_id/todo_items/:id
  # DELETE /todo_lists/:todo_list_id/todo_items/:id.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id]) #scope its find command to the todo_items of a specific @todo_list list
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.paginate(page: params[:page], per_page: 8)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:list_name, :list_due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <div style='float: right;'>
    Logged in as <%= current_user.username %> |
    <%= link_to "Logout", logout_path, method: :delete %>
  </div>
<% end %>
<% flash.each do |key, val| %>
  <p id='<%= key %>'> <%= val %> </p>
<% end %>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_item]) do |f| %> <!-- /todo_lists/:todo_list_id/todo_items/:id/edit -->
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <% if @todo_item.persisted? %>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>
<%= render 'form' %>
<%= link_to 'Show', [@todo_list, @todo_item] %> <!-- /todo_lists/:todo_list_id/todo_items/:id/edit --> |
<%= link_to 'Back', @todo_list %> <!-- /todo_lists/:id -->

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @todo_list %>

app/views/todo_items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<!-- #/todo_lists/:todo_list_id(@todo_list)/todo_items/:id(@todo_item)/edit -->
<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, @todo_item) %> |
<!-- #/todo_lists/:id(@todo_list) -->
<%= link_to 'Back', @todo_list %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %><br>
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_due_date %><br>
    <%= f.date_select :list_due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.list_name %></td>
        <td><%= todo_list.list_due_date %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<%= will_paginate @todo_lists %>
<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<!-- bacause the todo item is a nested resource we embed the listing of the todo items in the show of a particular todo list -->
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.title %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.completed %></td>
        <td><%= link_to 'Show', [@todo_list, todo_item] %></td>
        <td><%= link_to 'Destroy', [@todo_list, todo_item], method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>List name:</strong>
  <%= @todo_list.list_name %>
</p>

<p>
  <strong>List due date:</strong>
  <%= @todo_list.list_due_date %>
</p>
<%= link_to 'New Todo Item', new_todo_list_todo_item_path(@todo_list) %> |
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>